# Generated by Django 5.0.6 on 2024-07-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("soils", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="soils",
            old_name="ph",
            new_name="ph_level",
        ),
    ]
