# Generated by Django 5.0.6 on 2024-07-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SingleSoil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("ph_level", models.FloatField()),
                ("nutrients", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "soils_single_soil",
            },
        ),
    ]
