# Generated by Django 4.2.13 on 2024-07-10 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("singlesoil", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singlesoil",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="singlesoil",
            name="nutrients",
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name="singlesoil",
            table=None,
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "soil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plants",
                        to="singlesoil.singlesoil",
                    ),
                ),
            ],
        ),
    ]
