# Generated by Django 5.0.6 on 2024-07-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("singlesoil", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="singlesoil",
            table="soils_single_soil",
        ),
    ]
