# Generated by Django 5.0.6 on 2024-07-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("singlesoil", "0002_alter_singlesoil_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="singlesoil",
            table="soils_soils",
        ),
    ]
