# Generated by Django 5.0.6 on 2024-07-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("singlesoil", "0003_alter_singlesoil_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="singlesoil",
            table="soils_single_soil",
        ),
    ]
