# Generated by Django 5.0.6 on 2024-07-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customer",
            table="customer",
        ),
    ]
